### ISSUE TITLE
Problem in production environment

### ISSUE THREAD

**Issue by danielhz** [dennisreimann/masq#2]
It works fine in development environment, but I get this error when I use production:

```
Started GET "/" for 127.0.0.1 at Wed May 09 12:45:24 -0400 2012
Processing by Masq::InfoController#index as HTML
  Rendered /usr/lib/ruby/gems/1.8/gems/masq-0.1.0/app/views/masq/info/index.html.erb within layouts/masq/application (32.4ms)
  Rendered public/404.html (0.5ms)
Completed 404 Not Found in 223ms (Views: 3.8ms | ActiveRecord: 18.1ms)
```

**Comment by dennisreimann** [comment]
Could you try referencing the edge version of masq in your Gemfile and see if the error still occurs?

```
gem 'masq', github: 'dbloete/masq'
```

I've just setup a production app for myself to verify that it works and for me it does.
If it still does not work for you, can you give some more details, like how your routes file looks?

**Comment by danielhz** [comment]
I got the same error:

```
Started GET "/" for 127.0.0.1 at Fri May 11 10:06:38 -0400 2012
Processing by Masq::InfoController#index as HTML
  Rendered /home/daniel/.bundler/ruby/1.8/masq-90408f72893d/app/views/masq/info/index.html.erb within layouts/masq/application (29.5ms)
  Rendered public/404.html (0.8ms)
Completed 404 Not Found in 265ms (Views: 14.0ms | ActiveRecord: 46.9ms)
```

but it works fine if I don't put "-e production" when I run the server.

**Comment by dennisreimann** [comment]
What's your setup? I see that you are using Ruby 1.8, I'm running it under 1.9.3 and haven't tested it with 1.8, but it should work. What does your routes.rb look like?

**Comment by danielhz** [comment]
It looks exactly like this:

```
OpenidDeguCl::Application.routes.draw do
  mount Masq::Engine => "/"
end
```

**Comment by dennisreimann** [comment]
Hmm, that's how I'm running it in production. Can you patch the gem sources and remove line 10-12 from ApplicationController (https://github.com/dbloete/masq/blob/master/app/controllers/masq/application_controller.rb#L10) to see what can't be found?

**Comment by danielhz** [comment]
There is a problem with the CSS and the PNG image.

```
Started GET "/" for 127.0.0.1 at Sat May 12 18:10:58 -0400 2012
Processing by Masq::InfoController#index as HTML
  Rendered gems/ruby/1.8/bundler/gems/masq-90408f72893d/app/views/masq/info/index.html.erb within layouts/masq/application (34.9ms)
Completed 200 OK in 104ms (Views: 72.4ms | ActiveRecord: 0.0ms)


Started GET "/assets/masq/openid_symbol-a310c603c22cab0c47d1fc14a005b5e8.png" for 127.0.0.1 at Sat May 12 18:10:58 -0400 2012
Processing by Masq::AccountsController#show as PNG
  Parameters: {"account"=>"assets/masq/openid_symbol-a310c603c22cab0c47d1fc14a005b5e8"}
Completed 500 Internal Server Error in 10ms

ActiveRecord::RecordNotFound (ActiveRecord::RecordNotFound):
  gems/ruby/1.8/bundler/gems/masq-90408f72893d/app/controllers/masq/accounts_controller.rb:8:in `show'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/abstract_controller/base.rb:167:in `process_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/abstract_controller/callbacks.rb:18:in `process_action'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:436:in `_run__109195959__process_action__453433196__callbacks'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `send'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `__run_callback'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:81:in `send'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/abstract_controller/callbacks.rb:17:in `process_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/notifications.rb:123:in `instrument'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/notifications.rb:123:in `instrument'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/params_wrapper.rb:205:in `process_action'
  gems/ruby/1.8/gems/activerecord-3.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/abstract_controller/base.rb:121:in `process'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/abstract_controller/rendering.rb:45:in `process'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal.rb:203:in `dispatch'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal.rb:246:in `action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:73:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:36:in `call'
  gems/ruby/1.8/gems/journey-1.0.3/lib/journey/router.rb:68:in `call'
  gems/ruby/1.8/gems/journey-1.0.3/lib/journey/router.rb:56:in `each'
  gems/ruby/1.8/gems/journey-1.0.3/lib/journey/router.rb:56:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:600:in `call'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/engine.rb:479:in `call'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in `send'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in `method_missing'
  gems/ruby/1.8/gems/journey-1.0.3/lib/journey/router.rb:68:in `call'
  gems/ruby/1.8/gems/journey-1.0.3/lib/journey/router.rb:56:in `each'
  gems/ruby/1.8/gems/journey-1.0.3/lib/journey/router.rb:56:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:600:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/etag.rb:23:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/conditionalget.rb:25:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/head.rb:14:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/flash.rb:242:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/cookies.rb:338:in `call'
  gems/ruby/1.8/gems/activerecord-3.2.3/lib/active_record/query_cache.rb:64:in `call'
  gems/ruby/1.8/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:467:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `call'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `_run__397314981__call__4__callbacks'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `send'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `__run_callback'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:81:in `send'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/rack/logger.rb:26:in `call_app'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/rack/logger.rb:16:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/runtime.rb:17:in `call'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/lock.rb:15:in `call'
  gems/ruby/1.8/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
  gems/ruby/1.8/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
  gems/ruby/1.8/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
  gems/ruby/1.8/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
  gems/ruby/1.8/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/engine.rb:479:in `call'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/application.rb:220:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/content_length.rb:14:in `call'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/rack/log_tailer.rb:14:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/handler/webrick.rb:59:in `service'
  /usr/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  /usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/handler/webrick.rb:13:in `run'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/server.rb:265:in `start'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/commands/server.rb:70:in `start'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/commands.rb:55
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/commands.rb:50:in `tap'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/commands.rb:50
  script/rails:6:in `require'
  script/rails:6




Started GET "/assets/masq/application-0ea5e6346a7ac1e91d8132360fdd4f8f.css" for 127.0.0.1 at Sat May 12 18:10:58 -0400 2012
Processing by Masq::AccountsController#show as CSS
  Parameters: {"account"=>"assets/masq/application-0ea5e6346a7ac1e91d8132360fdd4f8f"}
Completed 500 Internal Server Error in 12ms

ActiveRecord::RecordNotFound (ActiveRecord::RecordNotFound):
  gems/ruby/1.8/bundler/gems/masq-90408f72893d/app/controllers/masq/accounts_controller.rb:8:in `show'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/abstract_controller/base.rb:167:in `process_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/abstract_controller/callbacks.rb:18:in `process_action'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:436:in `_run__109195959__process_action__453433196__callbacks'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `send'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `__run_callback'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:81:in `send'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/abstract_controller/callbacks.rb:17:in `process_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/notifications.rb:123:in `instrument'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/notifications.rb:123:in `instrument'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/params_wrapper.rb:205:in `process_action'
  gems/ruby/1.8/gems/activerecord-3.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/abstract_controller/base.rb:121:in `process'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/abstract_controller/rendering.rb:45:in `process'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal.rb:203:in `dispatch'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_controller/metal.rb:246:in `action'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:73:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:36:in `call'
  gems/ruby/1.8/gems/journey-1.0.3/lib/journey/router.rb:68:in `call'
  gems/ruby/1.8/gems/journey-1.0.3/lib/journey/router.rb:56:in `each'
  gems/ruby/1.8/gems/journey-1.0.3/lib/journey/router.rb:56:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:600:in `call'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/engine.rb:479:in `call'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in `send'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in `method_missing'
  gems/ruby/1.8/gems/journey-1.0.3/lib/journey/router.rb:68:in `call'
  gems/ruby/1.8/gems/journey-1.0.3/lib/journey/router.rb:56:in `each'
  gems/ruby/1.8/gems/journey-1.0.3/lib/journey/router.rb:56:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:600:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/etag.rb:23:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/conditionalget.rb:25:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/head.rb:14:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/flash.rb:242:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/cookies.rb:338:in `call'
  gems/ruby/1.8/gems/activerecord-3.2.3/lib/active_record/query_cache.rb:64:in `call'
  gems/ruby/1.8/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:467:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `call'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `_run__397314981__call__4__callbacks'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `send'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `__run_callback'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:81:in `send'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/rack/logger.rb:26:in `call_app'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/rack/logger.rb:16:in `call'
  gems/ruby/1.8/gems/actionpack-3.2.3/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/runtime.rb:17:in `call'
  gems/ruby/1.8/gems/activesupport-3.2.3/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/lock.rb:15:in `call'
  gems/ruby/1.8/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
  gems/ruby/1.8/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
  gems/ruby/1.8/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
  gems/ruby/1.8/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
  gems/ruby/1.8/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/engine.rb:479:in `call'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/application.rb:220:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/content_length.rb:14:in `call'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/rack/log_tailer.rb:14:in `call'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/handler/webrick.rb:59:in `service'
  /usr/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  /usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/handler/webrick.rb:13:in `run'
  gems/ruby/1.8/gems/rack-1.4.1/lib/rack/server.rb:265:in `start'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/commands/server.rb:70:in `start'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/commands.rb:55
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/commands.rb:50:in `tap'
  gems/ruby/1.8/gems/railties-3.2.3/lib/rails/commands.rb:50
  script/rails:6:in `require'
  script/rails:6
```

**Comment by dennisreimann** [comment]
This looks like, Rails expects your assets to be precompiled, but they aren't. I don't get why it raises an ActiveRecord::RecordNotFound though, because I'm getting this, when I try to reproduce it

```
Started GET "/" for 127.0.0.1 at 2012-05-14 22:12:52 +0200
Processing by Masq::InfoController#index as HTML
  Rendered /Users/dbloete/Sites/masq/app/views/masq/info/index.html.erb within layouts/masq/application (104.1ms)
Completed 500 Internal Server Error in 117ms

ActionView::Template::Error (masq/application.css isn't precompiled)
```

**Comment by jip149** [comment]
I had the same issue and fixed it by setting config.assets.compile to true in config/environments/production.rb

**Comment by dennisreimann** [comment]
It depends on your needs, you could also precompile the assets as a part of your production deployment process, so that they do not need to get compiled on the first request.
